name: Amazon Linux 2

on: [push]

jobs:
  linux:
    name: Amazon Linux 2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
          - 5.5.2
        distro:
          - amazonlinux2
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: Scripts/docker.sh Termbox 'swift build -Xswiftc -warnings-as-errors' ${{ matrix.swift }} ${{ matrix.distro }}
