name: macOS 11.15

on: [push]

jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    strategy:
      matrix:
        xcode:
          - 13.2.1
        action:
          - SwiftPM
    steps:
    - uses: actions/checkout@v2
    - name: Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Test
      run: make test-${{ matrix.action }}
